name: Docker Image CI for Soil Pred

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest #should be julia

    steps:
    - name: checkout code from current repo main/master branch
      uses: actions/checkout@v3

    - name: Set image meta attributes
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.REGISTRY_USER }}/soil_mir_predengine
        # generate Docker tags based on the following events/attributes
        tags: |
          type=sha
          latest

    # use buildx to speed up things and is recomended 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to DockerHub
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    # builld image 
    - name: build and push to docker
      uses: docker/build-push-action@v4
      with:

        context: .
        push: true
        #file: ./${{ secrets.DOCKERFILE }}
        tags: ${{ steps.meta.outputs.tags }}
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Log out on dockerhub registry
      run: docker logout